# Chapter 5. Getting Started with pandas

## Series

In [1]:
import numpy as np
import pandas as pd

In [2]:
s = pd.Series([1, 2])

In [3]:
s.values

array([1, 2])

In [4]:
s.index

RangeIndex(start=0, stop=2, step=1)

In [5]:
s2 = np.exp(s)
s2

0    2.718282
1    7.389056
dtype: float64

In [6]:
s2.values

array([2.71828183, 7.3890561 ])

In [7]:
s

0    1
1    2
dtype: int64

In [8]:
0 in s # Checking index like dict

True

In [9]:
sdict = pd.Series({'b': 10, 'a': 2})
sdict

b    10
a     2
dtype: int64

In [10]:
# specify the order of keys
sdict2 = pd.Series({'b': 10, 'a': 2}, index=['a','b','c'])
sdict2

a     2.0
b    10.0
c     NaN
dtype: float64

In [11]:
sdict + sdict2

a     4.0
b    20.0
c     NaN
dtype: float64

In [12]:
s

0    1
1    2
dtype: int64

In [13]:
s.name = "series name"
s

0    1
1    2
Name: series name, dtype: int64

In [14]:
s.index.name = "index name"
s

index name
0    1
1    2
Name: series name, dtype: int64

## DataFrame

In [15]:
df = pd.DataFrame({'a': [1,2,3], 'b': ['1','2','3']}, index=['aa', 'bb', 'cc'])
df

a  b
aa  1  1
bb  2  2
cc  3  3

In [16]:
bb = df.loc['bb']
bb

a    2
b    2
Name: bb, dtype: object

In [17]:
bb.index

Index(['a', 'b'], dtype='object')

In [18]:
bb.values

array([2, '2'], dtype=object)

In [19]:
bb[0] = 10 # this is not a view
bb

<ipython-input-19-ab62b38ea6c7>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bb[0] = 10 # this is not a view


a    10
b     2
Name: bb, dtype: object

In [20]:
a = df['a']
a

aa    1
bb    2
cc    3
Name: a, dtype: int64

In [21]:
a['aa'] = 10 # this is a view
a

<ipython-input-21-5b13d18ca389>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  a['aa'] = 10 # this is a view


aa    10
bb     2
cc     3
Name: a, dtype: int64

In [22]:
df

a  b
aa  10  1
bb   2  2
cc   3  3

In [23]:
df.columns.name = 'alphabet'
df

alphabet   a  b
aa        10  1
bb         2  2
cc         3  3

In [24]:
df.index.name = 'double alphabet'
df

alphabet          a  b
double alphabet       
aa               10  1
bb                2  2
cc                3  3

In [25]:
df.values

array([[10, '1'],
       [2, '2'],
       [3, '3']], dtype=object)

## Index Object

In [26]:
index = s.index
index

RangeIndex(start=0, stop=2, step=1, name='index name')

In [27]:
try:
    index[0] = 1  # immutable
except TypeError as e:
    print(e)

Index does not support mutable operations


In [28]:
# index is like a fixed-size set but with duplicate elements
index.intersection(index)

RangeIndex(start=0, stop=2, step=1, name='index name')

## Indexing, Selection, and Filtering

In [29]:
df

alphabet          a  b
double alphabet       
aa               10  1
bb                2  2
cc                3  3

In [30]:
df['b':'cc'] # slicing with labels is inclusive

alphabet         a  b
double alphabet      
bb               2  2
cc               3  3

In [31]:
df['a':'cc']

alphabet          a  b
double alphabet       
aa               10  1
bb                2  2
cc                3  3

In [32]:
df['aa':'cc']

alphabet          a  b
double alphabet       
aa               10  1
bb                2  2
cc                3  3

## Integer Indexes

In [33]:
ser = pd.Series(np.arange(3))
ser

0    0
1    1
2    2
dtype: int64

In [34]:
try:
    ser[-1]
except KeyError as e:
    print(repr(e))

KeyError(-1)


In [35]:
ser[:-1]

0    0
1    1
dtype: int64

In [36]:
ser2 = pd.Series(np.arange(3), index=['a', 'b', 'c'])
ser2

a    0
b    1
c    2
dtype: int64

In [37]:
ser2[-1]

2

In [38]:
ser2[:-1]

a    0
b    1
dtype: int64

## Function Application and Mapping

In [39]:
df = pd.DataFrame(np.random.randn(4,3))
df

0         1         2
0 -2.644391 -1.352065  0.569712
1  1.238952  0.499751  1.585260
2 -1.130029  1.654390 -1.318353
3  0.928706  0.315854  0.846063

In [40]:
np.abs(df)

0         1         2
0  2.644391  1.352065  0.569712
1  1.238952  0.499751  1.585260
2  1.130029  1.654390  1.318353
3  0.928706  0.315854  0.846063

In [41]:
f = lambda x: x.max() - x.min()

In [42]:
df.apply(f) # column-wise 

0    3.883343
1    3.006454
2    2.903612
dtype: float64

In [43]:
# row-wise (across columns)
df.apply(f, axis='columns')

0    3.214104
1    1.085509
2    2.972742
3    0.612852
dtype: float64

In [44]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [45]:
df.apply(f)

0         1         2
min -2.644391 -1.352065 -1.318353
max  1.238952  1.654390  1.585260

In [46]:
# Element-wise
format = lambda x: '%.2f' % x

In [47]:
df.applymap(format)

0      1      2
0  -2.64  -1.35   0.57
1   1.24   0.50   1.59
2  -1.13   1.65  -1.32
3   0.93   0.32   0.85

In [48]:
df[0].map(format)

0    -2.64
1     1.24
2    -1.13
3     0.93
Name: 0, dtype: object

In [49]:
s = pd.Series([1, 0, 2, 2])
s

0    1
1    0
2    2
3    2
dtype: int64

In [50]:
s.rank()

0    2.0
1    1.0
2    3.5
3    3.5
dtype: float64

In [51]:
s.rank(method='first')

0    2.0
1    1.0
2    3.0
3    4.0
dtype: float64

In [52]:
s.rank(ascending=False)

0    3.0
1    4.0
2    1.5
3    1.5
dtype: float64

In [53]:
s.rank(method='max')

0    2.0
1    1.0
2    4.0
3    4.0
dtype: float64

## XML and HTML: Web Scraping

In [54]:
tables = pd.read_html('pydata-book/examples/fdic_failed_bank_list.html')

In [56]:
tables[0].head()

Bank Name             City  ST   CERT  \
0                   Allied Bank         Mulberry  AR     91   
1  The Woodbury Banking Company         Woodbury  GA  11297   
2        First CornerStone Bank  King of Prussia  PA  35312   
3            Trust Company Bank          Memphis  TN   9956   
4    North Milwaukee State Bank        Milwaukee  WI  20364   

                 Acquiring Institution        Closing Date       Updated Date  
0                         Today's Bank  September 23, 2016  November 17, 2016  
1                          United Bank     August 19, 2016  November 17, 2016  
2  First-Citizens Bank & Trust Company         May 6, 2016  September 6, 2016  
3           The Bank of Fayette County      April 29, 2016  September 6, 2016  
4  First-Citizens Bank & Trust Company      March 11, 2016      June 16, 2016