# Chapter 5. Getting Started with pandas

## Series

In [1]:
import numpy as np
import pandas as pd

In [2]:
s = pd.Series([1, 2])

In [4]:
s.values

array([1, 2])

In [6]:
s.index

RangeIndex(start=0, stop=2, step=1)

In [9]:
s2 = np.exp(s)
s2

0    2.718282
1    7.389056
dtype: float64

In [10]:
s2.values

array([2.71828183, 7.3890561 ])

In [11]:
s

0    1
1    2
dtype: int64

In [13]:
0 in s # Checking index like dict

True

In [16]:
sdict = pd.Series({'b': 10, 'a': 2})
sdict

b    10
a     2
dtype: int64

In [19]:
# specify the order of keys
sdict2 = pd.Series({'b': 10, 'a': 2}, index=['a','b','c'])
sdict2

a     2.0
b    10.0
c     NaN
dtype: float64

In [20]:
sdict + sdict2

a     4.0
b    20.0
c     NaN
dtype: float64

In [21]:
s

0    1
1    2
dtype: int64

In [22]:
s.name = "series name"
s

0    1
1    2
Name: series name, dtype: int64

In [23]:
s.index.name = "index name"
s

index name
0    1
1    2
Name: series name, dtype: int64

## DataFrame

In [25]:
df = pd.DataFrame({'a': [1,2,3], 'b': ['1','2','3']}, index=['aa', 'bb', 'cc'])
df

a  b
aa  1  1
bb  2  2
cc  3  3

In [27]:
bb = df.loc['bb']
bb

a    2
b    2
Name: bb, dtype: object

In [28]:
bb.index

Index(['a', 'b'], dtype='object')

In [29]:
bb.values

array([2, '2'], dtype=object)

In [35]:
bb[0] = 10 # this is not a view
bb

/Users/hugh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


a    10
b     2
Name: bb, dtype: object

In [38]:
a = df['a']
a

aa    1
bb    2
cc    3
Name: a, dtype: int64

In [39]:
a['aa'] = 10 # this is a view
a

/Users/hugh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


aa    10
bb     2
cc     3
Name: a, dtype: int64

In [40]:
df

a  b
aa  10  1
bb   2  2
cc   3  3

In [42]:
df.columns.name = 'alphabet'
df

alphabet   a  b
aa        10  1
bb         2  2
cc         3  3

In [43]:
df.index.name = 'double alphabet'
df

alphabet          a  b
double alphabet       
aa               10  1
bb                2  2
cc                3  3

In [44]:
df.values

array([[10, '1'],
       [2, '2'],
       [3, '3']], dtype=object)

## Index Object

In [45]:
index = s.index
index

RangeIndex(start=0, stop=2, step=1, name='index name')

In [49]:
try:
    index[0] = 1  # immutable
except TypeError as e:
    print(e)

Index does not support mutable operations


In [50]:
# index is like a fixed-size set but with duplicate elements
index.intersection(index)

RangeIndex(start=0, stop=2, step=1, name='index name')

## Indexing, Selection, and Filtering

In [51]:
df

alphabet          a  b
double alphabet       
aa               10  1
bb                2  2
cc                3  3

In [53]:
df['b':'cc'] # slicing with labels is inclusive

alphabet         a  b
double alphabet      
bb               2  2
cc               3  3